# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZPA8dJEpHGWU1gztO9ocKDQGB4UWZRGY
"""

import numpy as np
import matplotlib.pyplot as plt

# Sistema de ecuaciones
def f(t, y):
    y1, y2 = y
    dy1 = y2
    dy2 = 1.5 * (1 - y1**2) * y2 - y1
    return np.array([dy1, dy2])

# Condiciones iniciales
t = 0
y = np.array([2.0, 0.0])

h = 0.05
tf = 20

# Listas para guardar resultados
T = [t]
X = [y[0]]
V = [y[1]]

print("Primeras 10 iteraciones")
print("Iter\t t\t\t x(t)\t\t v(t)")

iteracion = 0

while t < tf:

    k1 = f(t, y)
    k2 = f(t + h/2, y + h*k1/2)
    k3 = f(t + h/2, y + h*k2/2)
    k4 = f(t + h, y + h*k3)

    y = y + (h/6)*(k1 + 2*k2 + 2*k3 + k4)
    t = t + h

    # Guardar resultados
    T.append(t)
    X.append(y[0])
    V.append(y[1])

    # Mostrar solo las primeras 10 iteraciones
    if iteracion < 10:
        print(f"{iteracion+1}\t {t:.2f}\t\t {y[0]:.6f}\t {y[1]:.6f}")

    iteracion += 1

# Estado final
print("\nEstado final")
print(f"t  = {t:.2f}")
print(f"x(t) = {y[0]:.6f}")
print(f"v(t) = {y[1]:.6f}")

# ==========================
# Gráfica 1: x(t) y v(t)
# ==========================
plt.figure(figsize=(8,5))
plt.plot(T, X, label="x(t)")
plt.plot(T, V, label="v(t)")
plt.xlabel("Tiempo (s)")
plt.ylabel("Valor")
plt.title("Evolución temporal de x(t) y v(t)")
plt.grid(True)
plt.legend()
plt.show()

# ==========================
# Gráfica 2: Espacio de fases
# ==========================
plt.figure(figsize=(6,6))
plt.plot(X, V)
plt.xlabel("x(t)")
plt.ylabel("v(t)")
plt.title("Diagrama de espacio de fases")
plt.grid(True)
plt.show()